import = ["~/.config/alacritty/themes/themes/nordic.toml"]

[font]
size = 12.5

[font.normal]
family = "JetBrainsMono Nerd Font"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Alt"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Alt"

[scrolling]
history = 0

[window]
decorations = "full"
